### ISSUE TITLE
Migration functionality results in 'dict' object has no attribute error

### ISSUE THREAD

**Issue by ahmadadam96** [eclipse-fog05/api-python#8]
When trying to migrate an LXD container from its current node to another one (using the function `api.fdu.migrate(UUID of instance,UUID of destination node)` ). This error is the result.

```
fdu_id : d790a23d-ee56-5645-8c8d-fb014d9c4776
Instance ID : fc9cd2c2-388b-4223-a05b-21db02c140b9
Traceback (most recent call last):
  File "fos_deploy.py", line 25, in <module>
    inst_info = api.fdu.migrate(inst_info.get_uuid(), n2)
  File "/usr/local/lib/python3.6/dist-packages/fog05-0.1.0-py3.6.egg/fog05/fimapi.py", line 1124, in migrate
AttributeError: 'dict' object has no attribute 'get_fdu_id'

```

**Comment by gabrik** [comment]
Thank @ahmadadam96 for reporting this, 
Can you try the code of #9 and report if it is working?

**Comment by ahmadadam96** [comment]
Hi @gabrik , I just tried it out and it works for me. Thanks a lot! While testing it I discovered that the migrate functionality on my machine replicates the instance on the other node. So the instance is running on both nodes. Is this the intended functionality?

**Comment by gabrik** [comment]
Hi @ahmadadam96,
No, the intended functionality is that the container on the source node is stopped and then destroyed. 
If you still see it running, using `lxc list`, please open an issue on the LXD plugin (https://github.com/eclipse-fog05/plugin-fdu-lxd/) with the output of `journalctl -u fos_lxd -f` from the source node.
